backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow
# This line should *not* be indented
media_folder: 'images/'

collections:
  - name: 'books' # Used in routes, e.g., /admin/collections/blog
    label: 'Books' # Used in the UI
    folder: 'pages/markdown/books' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Author', name: 'author', widget: 'string', required: true }
      - { label: 'Translator', name: 'translator', widget: 'string' }
      - {
          label: 'Publisher',
          name: 'publisher',
          widget: 'string',
          required: true,
        }
      - { label: 'Publish Date', name: 'publish_date', widget: 'datetime' }
      - {
          label: 'Cover Image',
          name: 'thumbnail',
          widget: 'image',
          required: true,
        }
      - { label: 'Mockup Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Notes', name: 'notes', widget: 'text' }
      - {
          label: 'Type',
          name: 'type',
          widget: 'list',
          required: true,
          fields: ['book'],
        }
      - {
          label: 'Featured',
          name: 'featured',
          widget: 'boolean',
          required: true,
        }

  - name: 'artworks' # Used in routes, e.g., /admin/collections/blog
    label: 'Artworks' # Used in the UI
    folder: 'pages/markdown/art' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Translator', name: 'translator', widget: 'string' }
      - { label: 'Publisher', name: 'publisher', widget: 'string' }
      - { label: 'Publish Date', name: 'publish_date', widget: 'datetime' }
      - {
          label: 'Cover Image',
          name: 'thumbnail',
          widget: 'image',
          required: true,
        }
      - { label: 'Mockup Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Notes', name: 'notes', widget: 'text' }
      - {
          label: 'Type',
          name: 'type',
          widget: 'list',
          required: true,
          fields: ['art'],
        }
      - {
          label: 'Featured',
          name: 'featured',
          widget: 'boolean',
          required: true,
        }

  - name: 'campaign' # Used in routes, e.g., /admin/collections/blog
    label: 'Campaigns' # Used in the UI
    folder: 'pages/markdown/campaigns' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Author', name: 'author', widget: 'string', required: true }
      - { label: 'Translator', name: 'translator', widget: 'string' }
      - { label: 'Publisher', name: 'publisher', widget: 'string' }
      - { label: 'Publish Date', name: 'publish_date', widget: 'datetime' }
      - {
          label: 'Cover Image',
          name: 'thumbnail',
          widget: 'image',
          required: true,
        }
      - { label: 'Mockup Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Notes', name: 'notes', widget: 'text' }
      - {
          label: 'Type',
          name: 'type',
          widget: 'list',
          required: true,
          fields: ['campaign'],
        }
      - {
          label: 'Featured',
          name: 'featured',
          widget: 'boolean',
          required: true,
        }
