backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow
# This line should *not* be indented
media_folder: 'src/images'
# public_folder: '/images'

collections:
  - name: 'books' # Used in routes, e.g., /admin/collections/blog
    label: 'Books' # Used in the UI
    folder: 'src/pages/markdown/books' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}_{{title}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Author', name: 'author', widget: 'string', required: true }
      - {
          label: 'Translator',
          name: 'translator',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Publisher',
          name: 'publisher',
          widget: 'string',
          required: true,
        }
      - {
          label: 'Publish Date',
          name: 'publish_date',
          widget: 'datetime',
          required: false,
        }
      - { label: 'Cover Image', name: 'cover', widget: 'image', required: true }
      - {
          label: 'Mockup Image',
          name: 'mockup',
          widget: 'image',
          required: false,
        }
      - { label: 'Notes', name: 'notes', widget: 'text', required: false }
      - { label: 'Type', name: 'type', widget: 'hidden', default: 'book' }
      - {
          label: 'Featured',
          name: 'featured',
          widget: 'boolean',
          required: true,
        }

  - name: 'artworks' # Used in routes, e.g., /admin/collections/blog
    label: 'Artworks' # Used in the UI
    folder: 'src/pages/markdown/artwork' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}_{{title}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Author', name: 'author', widget: 'hidden' }
      - { label: 'Translator', name: 'translator', widget: 'hidden' }
      - { label: 'Publisher', name: 'publisher', widget: 'hidden' }
      - { label: 'Publish Date', name: 'publish_date', widget: 'hidden' }
      - { label: 'Cover Image', name: 'cover', widget: 'image', required: true }
      - { label: 'Mockup Image', name: 'mockup', widget: 'hidden' }
      - { label: 'Notes', name: 'notes', widget: 'text', required: false }
      - { label: 'Type', name: 'type', widget: 'hidden', default: 'work_art' }
      - {
          label: 'Featured',
          name: 'featured',
          widget: 'boolean',
          required: true,
        }

  - name: 'campaign' # Used in routes, e.g., /admin/collections/blog
    label: 'Campaigns' # Used in the UI
    folder: 'src/pages/markdown/campaigns' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}_{{title}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Author', name: 'author', widget: 'hidden' }
      - { label: 'Translator', name: 'translator', widget: 'hidden' }
      - {
          label: 'Publisher',
          name: 'publisher',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Publish Date',
          name: 'publish_date',
          widget: 'datetime',
          required: false,
        }
      - { label: 'Cover Image', name: 'cover', widget: 'image', required: true }
      - {
          label: 'Mockup Image',
          name: 'mockup',
          widget: 'image',
          required: false,
        }
      - { label: 'Notes', name: 'notes', widget: 'text', required: false }
      - { label: 'Type', name: 'type', widget: 'hidden', default: 'campaign' }
      - {
          label: 'Featured',
          name: 'featured',
          widget: 'boolean',
          required: true,
        }

  - name: 'about' # Used in routes, e.g., /admin/collections/blog
    label: 'About' # Used in the UI
    folder: 'src/pages/markdown/about' # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Type', name: 'type', widget: 'hidden', default: 'about' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
